import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react";

const config = defineConfig({
    globalCss: {
        "html, body": {
            bg: { base: "bg.canvas" },
        },
    },
    theme: {
        breakpoints: {
            sm: "480px",
            md: "768px",
            lg: "1024px",
            xl: "1280px",
            xxl: "1546px",
        },
        tokens: {
            colors: {
                teal: {
                    DEFAULT: { value: "#1A1A2E" },
                    50: { value: "#FCFCFD" },
                    100: { value: "#ECECF4" },
                    200: { value: "#CBCBE2" },
                    300: { value: "#ABABCF" },
                    400: { value: "#8A8ABD" },
                    500: { value: "#6A6AAB" },
                    600: { value: "#515190" },
                    700: { value: "#3F3F6F" },
                    800: { value: "#2C2C4F" },
                    900: { value: "#1A1A2E" },
                },
                laguna: {
                    DEFAULT: { value: "#1B9AD6" },
                    50: { value: "#DCF1FB" },
                    100: { value: "#C5E8F8" },
                    200: { value: "#98D5F2" },
                    300: { value: "#6BC3EC" },
                    400: { value: "#3DB0E7" },
                    500: { value: "#1B9AD6" },
                    600: { value: "#1579A9" },
                    700: { value: "#10597B" },
                    800: { value: "#0A384E" },
                    900: { value: "#041821" },
                },
                teal: {
                    DEFAULT: { value: "#0D7FAF" },
                    50: { value: "#D8F2FC" },
                    100: { value: "#C1E9FA" },
                    200: { value: "#91D9F7" },
                    300: { value: "#62C8F3" },
                    400: { value: "#32B8F0" },
                    500: { value: "#11A1DE" },
                    600: { value: "#0D7FAF" },
                    700: { value: "#095D80" },
                    800: { value: "#063A50" },
                    900: { value: "#021821" },
                },
                cerro: {
                    DEFAULT: { value: "#4A5568" },
                    50: { value: "#FFFFFF" },
                    100: { value: "#F0F1F4" },
                    200: { value: "#D2D7DF" },
                    300: { value: "#B4BCCA" },
                    400: { value: "#96A1B5" },
                    500: { value: "#79879F" },
                    600: { value: "#5F6D86" },
                    700: { value: "#4A5568" },
                    800: { value: "#353D4A" },
                    900: { value: "#20242C" },
                },
                bosque: {
                    DEFAULT: { value: "#2D6A4F" },
                    50: { value: "#ECF7F2" },
                    100: { value: "#DAEFE6" },
                    200: { value: "#B6E0CD" },
                    300: { value: "#92D1B5" },
                    400: { value: "#6EC29D" },
                    500: { value: "#4BB284" },
                    600: { value: "#3C8E6A" },
                    700: { value: "#2D6A4F" },
                    800: { value: "#1E4634" },
                    900: { value: "#0F221A" },
                },
                presa: {
                    DEFAULT: { value: "#52B788" },
                    50: { value: "#F4FAF7" },
                    100: { value: "#E2F3EB" },
                    200: { value: "#BEE4D2" },
                    300: { value: "#9AD5BA" },
                    400: { value: "#76C6A1" },
                    500: { value: "#52B788" },
                    600: { value: "#3F976E" },
                    700: { value: "#307354" },
                    800: { value: "#214F3A" },
                    900: { value: "#122B1F" },
                },
                trail: {
                    DEFAULT: { value: "#F59E0B" },
                    50: { value: "#FEF6E7" },
                    100: { value: "#FDECCF" },
                    200: { value: "#FBD89E" },
                    300: { value: "#F9C56D" },
                    400: { value: "#F7B13C" },
                    500: { value: "#F59E0B" },
                    600: { value: "#C57F08" },
                    700: { value: "#945F06" },
                    800: { value: "#634004" },
                    900: { value: "#322002" },
                },
                nieve: {
                    DEFAULT: { value: "#F7F8FA" },
                    50: { value: "#F7F8FA" },
                    100: { value: "#E7EAF0" },
                    200: { value: "#C8CFDD" },
                    300: { value: "#A9B3C9" },
                    400: { value: "#8998B5" },
                    500: { value: "#6A7CA2" },
                    600: { value: "#536485" },
                    700: { value: "#404C66" },
                    800: { value: "#2C3546" },
                    900: { value: "#181D27" },
                },
            },
            fonts: {
                heading: { value: "'Barlow Condensed', serif" },
                body: { value: "Inter, sans-serif"},
            },
            semanticTokens: {
                colors: {
                    bg: {
                        canvas: { value: "{colors.nieve}" },
                    },
                    accent: {
                        solid: { value: "{colors.trail}"},
                    },
                },
            },
        },
    },
})

export const system = createSystem(defaultConfig, config)